import mongoose from 'mongoose';

const vendorKycSchema = new mongoose.Schema(
  {
    vendorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Vendor',
      required: true,
      unique: true,
      index: true,
    },
    ownerPhoto: { type: String, default: '' },
    fullName: { type: String, default: '', trim: true },
    dateOfBirth: { type: Date, default: null },
    permanentAddress: { type: String, default: '', trim: true },
    contactNumber: { type: String, default: '', trim: true },
    panNumber: { type: String, default: '', trim: true, uppercase: true },
    aadhaarNumber: { type: String, default: '', trim: true },
    panPhoto: { type: String, default: '' },
    aadhaarFront: { type: String, default: '' },
    aadhaarBack: { type: String, default: '' },
    tshirtSize: { type: String, default: '' },
    jeansWaistSize: { type: String, default: '' },
    shoeSize: { type: String, default: '' },
    businessDetails: {
      shopName: { type: String, default: '', trim: true },
      businessCategory: { type: String, default: '', trim: true },
      shopActNumber: { type: String, default: '', trim: true },
      gstin: { type: String, default: '', trim: true },
      primaryContactNumber: { type: String, default: '', trim: true },
      secondaryContactNumber: { type: String, default: '', trim: true },
      shopActLicense: { type: String, default: '' },
      /** Original client filename for display (URL last segment is often a Cloudinary id). */
      shopActLicenseFileName: { type: String, default: '', trim: true },
      gstCertificate: { type: String, default: '' },
      gstCertificateFileName: { type: String, default: '', trim: true },
    },
    // bankDetails: {
    //   accountHolderName: { type: String, default: '', trim: true },
    //   accountNumber: { type: String, default: '', trim: true },
    //   confirmAccountNumber: { type: String, default: '', trim: true },
    //   ifscCode: { type: String, default: '', trim: true, uppercase: true },
    //   cancelledCheque: { type: String, default: '' },
    //   isDefault: { type: Boolean, default: false },
    // },

    bankDetails: {
      accountHolderName: { type: String, default: '', trim: true },
      accountNumber: { type: String, default: '', trim: true },
      confirmAccountNumber: { type: String, default: '', trim: true },
      ifscCode: { type: String, default: '', trim: true, uppercase: true },
      cancelledCheque: { type: String, default: '' },
      isDefault: { type: Boolean, default: false },
      status: {
        type: String,
        enum: ['Pending', 'Verified', 'Rejected'],
        default: 'Pending',
      },
      verified: { type: Boolean, default: false },
      rejectionReason: { type: String, default: '' },
      reviewedAt: { type: Date, default: null },
      reviewedBy: { type: String, default: '' },
    },
    storeManagement: {
      stores: [
        {
          storeName: { type: String, default: '', trim: true },
          completeAddress: { type: String, default: '', trim: true },
          pincode: { type: String, default: '', trim: true },
          city: { type: String, default: '', trim: true },
          mapLocation: { type: String, default: '', trim: true },
          mapAddress: { type: String, default: '', trim: true },
          mapLat: { type: Number, default: null },
          mapLng: { type: Number, default: null },
          shopFrontPhotoName: { type: String, default: '', trim: true },
          shopFrontPhotoUrl: { type: String, default: '' },
          additionalPhotoNames: [{ type: String, default: '' }],
          additionalPhotoUrls: [{ type: String, default: '' }],
          deliveryZoneType: {
            type: String,
            enum: ['pan-india', 'hyper-local'],
            default: 'pan-india',
          },
          serviceRadiusKm: { type: Number, default: 15 },
          serviceModeLocalDelivery: { type: Boolean, default: false },
          serviceModePanIndia: { type: Boolean, default: false },
          walkInAccessLabel: {
            type: String,
            default: 'No Public Access',
            trim: true,
          },
          isDefault: { type: Boolean, default: false },
          isActive: { type: Boolean, default: true },
          /** Timestamp when admin disabled this store (null when enabled). */
          disabledAt: { type: Date, default: null },
          /** Admin identifier (email) who last disabled this store. */
          disabledBy: { type: String, default: '', trim: true },
          allowsWalkIn: { type: Boolean, default: false },
          storeTimings: { type: String, default: '', trim: true },
        },
      ],
      slaAccepted: { type: Boolean, default: false },
      commissionAccepted: { type: Boolean, default: false },
    },
    currentStep: { type: Number, default: 1, min: 1, max: 4 },
    sectionsCompleted: {
      personal: { type: Boolean, default: false },
      business: { type: Boolean, default: false },
      banking: { type: Boolean, default: false },
      store: { type: Boolean, default: false },
    },
    applicationSubmitted: { type: Boolean, default: false },
    status: {
      type: String,
      enum: ['draft', 'pending', 'approved', 'rejected'],
      default: 'draft',
      index: true,
    },
    rejectionReason: { type: String, default: '' },
    adminComment: { type: String, default: '' },
    /** Per-document admin feedback: key -> { status, comment, updatedAt } */
    documentReviews: { type: mongoose.Schema.Types.Mixed, default: {} },
    awaitingVendorUpload: { type: Boolean, default: false },
    resubmittedPendingReview: { type: Boolean, default: false },
    reviewedAt: { type: Date, default: null },
    reviewedBy: { type: String, default: '' },
    submittedAt: { type: Date, default: Date.now },
  },
  { timestamps: true },
);

export default mongoose.model('VendorKyc', vendorKycSchema);
